// Ver https://msu.edu/course/mus/441/snapshot.afs/sullivan/fs2/MidiFiles/GenMidiInstList.html
export enum MidiInstrument {
  "acoustic-piano" = 0,
  "brtacou-piano" = 1,
  "elecgrand-piano" = 2,
  "honky-tonk-piano" = 3,
  "elec.piano-1" = 4,
  "elec.piano-2" = 5,
  "harsichord" = 6,
  "clavichord" = 7,
  "celesta" = 8,
  "glockenspiel" = 9,
  "music-box" = 10,
  "vibraphone" = 11,
  "marimba" = 12,
  "xylophone" = 13,
  "tubular-bells" = 14,
  "dulcimer" = 15,
  "drawbar-organ" = 16,
  "perc-organ" = 17,
  "rock-organ" = 18,
  "church-organ" = 19,
  "reed-organ" = 20,
  "accordian" = 21,
  "harmonica" = 22,
  "tango-accordian" = 23,
  "acoustic-guitar" = 24,
  "steelacous-guita" = 25,
  "eljazz-guitar" = 26,
  "electric-guitar" = 27,
  "el-muted-guitar" = 28,
  "overdriven-guita" = 29,
  "distortion-guita" = 30,
  "guitar-harmonic" = 31,
  "acoustic-bass" = 32,
  "el-bass-finger" = 33,
  "el-bass-pick" = 34,
  "fretless-bass" = 35,
  "slap-bass-1" = 36,
  "slap-bass-2" = 37,
  "synth-bass-1" = 38,
  "synth-bass-2" = 39,
  "violin" = 40,
  "viola" = 41,
  "cello" = 42,
  "contra-bass" = 43,
  "tremelo-strings" = 44,
  "pizz-strings" = 45,
  "orch-strings" = 46,
  "timpani" = 47,
  "string-ens.1" = 48,
  "string-ens.2" = 49,
  "synth.strings-1" = 50,
  "synth.strings-2" = 51,
  "choir-aahs" = 52,
  "voice-oohs" = 53,
  "synth-voice" = 54,
  "orchestra-hit" = 55,
  "trumpet" = 56,
  "trombone" = 57,
  "tuba" = 58,
  "muted-trumpet" = 59,
  "french-horn" = 60,
  "brass-section" = 61,
  "synth-brass-1" = 62,
  "synth-brass-2" = 63,
  "soprano-sax" = 64,
  "alto-sax" = 65,
  "tenor-sax" = 66,
  "baritone-sax" = 67,
  "oboe" = 68,
  "english-horn" = 69,
  "bassoon" = 70,
  "clarinet" = 71,
  "piccolo" = 72,
  "flute" = 73,
  "recorder" = 74,
  "pan-flute" = 75,
  "blown-bottle" = 76,
  "shakuhachi" = 77,
  "whistle" = 78,
  "ocarina" = 79,
  "lead1-square" = 80,
  "lead2-sawtooth" = 81,
  "lead3-calliope" = 82,
  "lead4-chiff" = 83,
  "lead5-charang" = 84,
  "lead6-voice" = 85,
  "lead7-fifths" = 86,
  "lead8-bass-ld" = 87,
  "pad1-new-age" = 88,
  "pad2-warm" = 89,
  "pad3-polysynth" = 90,
  "pad4-choir" = 91,
  "pad5-bowed" = 92,
  "pad6-metallic" = 93,
  "pad7-halo" = 94,
  "pad8-sweep" = 95,
  "fx1-rain" = 96,
  "fx2-soundtrack" = 97,
  "fx3-crystal" = 98,
  "fx4-atmosphere" = 99,
  "fx5-brightness" = 100,
  "fx6-goblins" = 101,
  "fx7-echoes" = 102,
  "fx8-sci-fi" = 103,
  "sitar" = 104,
  "banjo" = 105,
  "shamisen" = 106,
  "koto" = 107,
  "kalimba" = 108,
  "bagpipe" = 109,
  "fiddle" = 110,
  "shanai" = 111,
  "tinkerbell" = 112,
  "agogo" = 113,
  "steeldrums" = 114,
  "woodblock" = 115,
  "taikodrum" = 116,
  "melodic-tom" = 117,
  "synthdrum" = 118,
  "reverse-cymbal" = 119,
  "guitar-fret-nois" = 120,
  "breath-noise" = 121,
  "seashore" = 122,
  "birdtweet" = 123,
  "telephone" = 124,
  "helicopter" = 125,
  "applause" = 126,
  "gunshot" = 127,
}

export type Octave = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export type Pitch = "A" | "B" | "C" | "D" | "E" | "F" | "G";

export type MidiNote = {
  type: "NOTE";
  pitch: Pitch;
};

export type Command =
  | { type: "REPEAT_LAST_OR_SILENCE" }
  | { type: "DOUBLE_VOLUME" }
  | { type: "INCREASE_OCTAVE" }
  | { type: "CHANGE_INSTRUMENT"; value: MidiInstrument }
  | { type: "ADD_TO_INSTRUMENT_NUMBER"; value: number };

export type SoundEvent = MidiNote | Command;
